In [1]:
import pandas as pd
import numpy as np
import joblib ## for model exportation

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)

df = pd.read_csv("cleaned_data.csv", low_memory=False)
df

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance,Credit_Score,Credit-Builder Loan,Personal Loan,Debt Consolidation Loan,Student Loan,Payday Loan,Mortgage Loan,Auto Loan,Home Equity Loan,Occupation_Accountant,Occupation_Architect,Occupation_Developer,Occupation_Doctor,Occupation_Engineer,Occupation_Entrepreneur,Occupation_Journalist,Occupation_Lawyer,Occupation_Manager,Occupation_Mechanic,Occupation_Media_Manager,Occupation_Musician,Occupation_Scientist,Occupation_Teacher,Occupation_Writer,Payment_of_Min_Amount_No,Payment_of_Min_Amount_Yes,Payment_Behaviour_High_spent_Large_value_payments,Payment_Behaviour_High_spent_Medium_value_payments,Payment_Behaviour_High_spent_Small_value_payments,Payment_Behaviour_Low_spent_Large_value_payments,Payment_Behaviour_Low_spent_Medium_value_payments,Payment_Behaviour_Low_spent_Small_value_payments
0,23.0,19114.12,1824.843333,3.0,4.0,3.0,4.0,3.0,7.0,11.27,4.0,1.0,809.98,26.822620,265.0,49.574949,80.415295,312.494089,2,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0
1,23.0,19114.12,3095.978333,3.0,4.0,3.0,4.0,-1.0,14.0,11.27,4.0,2.0,809.98,31.944960,219.0,49.574949,118.280222,284.629162,2,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0
2,23.0,19114.12,3095.978333,3.0,4.0,3.0,4.0,5.0,4.0,6.27,4.0,2.0,809.98,31.377862,268.0,49.574949,199.458074,223.451310,2,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1
3,23.0,19114.12,1824.843333,3.0,4.0,3.0,4.0,6.0,14.0,11.27,4.0,2.0,809.98,24.797347,269.0,49.574949,41.420153,341.489231,2,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0
4,23.0,19114.12,3095.978333,3.0,4.0,3.0,4.0,8.0,4.0,9.27,4.0,2.0,809.98,27.262259,270.0,49.574949,62.430172,340.479212,2,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97219,25.0,39628.99,3359.415833,4.0,6.0,7.0,2.0,23.0,7.0,11.50,3.0,1.0,502.38,34.663572,378.0,35.104023,60.971333,479.866228,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0
97220,25.0,39628.99,3359.415833,4.0,6.0,7.0,2.0,18.0,7.0,11.50,3.0,1.0,502.38,40.565631,379.0,35.104023,54.185950,496.651610,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0
97221,25.0,39628.99,3359.415833,4.0,6.0,13.0,2.0,27.0,6.0,11.50,3.0,2.0,502.38,41.255522,380.0,35.104023,24.028477,516.809083,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0
97222,25.0,39628.99,3359.415833,4.0,6.0,7.0,2.0,20.0,14.0,11.50,3.0,2.0,502.38,33.638208,381.0,35.104023,251.672582,319.164979,1,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0
97223,25.0,39628.99,3359.415833,4.0,6.0,7.0,2.0,18.0,6.0,11.50,3.0,2.0,502.38,34.192463,382.0,35.104023,167.163865,393.673696,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1

In [3]:
df.dtypes

Age                                                   float64
Annual_Income                                         float64
Monthly_Inhand_Salary                                 float64
Num_Bank_Accounts                                     float64
Num_Credit_Card                                       float64
Interest_Rate                                         float64
Num_of_Loan                                           float64
Delay_from_due_date                                   float64
Num_of_Delayed_Payment                                float64
Changed_Credit_Limit                                  float64
Num_Credit_Inquiries                                  float64
Credit_Mix                                            float64
Outstanding_Debt                                      float64
Credit_Utilization_Ratio                              float64
Credit_History_Age                                    float64
Total_EMI_per_month                                   float64
Amount_invested_monthly                               float64
Monthly_Balance                                       float64
Credit_Score                                            int64
Credit-Builder Loan                                   float64
Personal Loan                                         float64
Debt Consolidation Loan                               float64
Student Loan                                          float64
Payday Loan                                           float64
Mortgage Loan                                         float64
Auto Loan                                             float64
Home Equity Loan                                      float64
Occupation_Accountant                                   int64
Occupation_Architect                                    int64
Occupation_Developer                                    int64
Occupation_Doctor                                       int64
Occupation_Engineer                                     int64
Occupation_Entrepreneur                                 int64
Occupation_Journalist                                   int64
Occupation_Lawyer                                       int64
Occupation_Manager                                      int64
Occupation_Mechanic                                     int64
Occupation_Media_Manager                                int64
Occupation_Musician                                     int64
Occupation_Scientist                                    int64
Occupation_Teacher                                      int64
Occupation_Writer                                       int64
Payment_of_Min_Amount_No                                int64
Payment_of_Min_Amount_Yes                               int64
Payment_Behaviour_High_spent_Large_value_payments       int64
Payment_Behaviour_High_spent_Medium_value_payments      int64
Payment_Behaviour_High_spent_Small_value_payments       int64
Payment_Behaviour_Low_spent_Large_value_payments        int64
Payment_Behaviour_Low_spent_Medium_value_payments       int64
Payment_Behaviour_Low_spent_Small_value_payments        int64
dtype: object

In [4]:
df2 = pd.read_csv("train.csv", low_memory=False)
df2['Month'].value_counts()

January     12500
February    12500
March       12500
April       12500
May         12500
June        12500
July        12500
August      12500
Name: Month, dtype: int64

In [7]:
df.sort_values(by='Age', ascending=True)

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance,Credit_Score,Credit-Builder Loan,Personal Loan,Debt Consolidation Loan,Student Loan,Payday Loan,Mortgage Loan,Auto Loan,Home Equity Loan,Occupation_Accountant,Occupation_Architect,Occupation_Developer,Occupation_Doctor,Occupation_Engineer,Occupation_Entrepreneur,Occupation_Journalist,Occupation_Lawyer,Occupation_Manager,Occupation_Mechanic,Occupation_Media_Manager,Occupation_Musician,Occupation_Scientist,Occupation_Teacher,Occupation_Writer,Payment_of_Min_Amount_No,Payment_of_Min_Amount_Yes,Payment_Behaviour_High_spent_Large_value_payments,Payment_Behaviour_High_spent_Medium_value_payments,Payment_Behaviour_High_spent_Small_value_payments,Payment_Behaviour_Low_spent_Large_value_payments,Payment_Behaviour_Low_spent_Medium_value_payments,Payment_Behaviour_Low_spent_Small_value_payments
37471,14.0,133444.08,10847.340000,5.0,3.0,13.0,7.0,12.0,13.0,17.04,11.0,1.0,217.91,28.832551,182.0,69.249473,744.576821,336.647778,1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
72885,14.0,36228.20,2991.016667,8.0,7.0,34.0,2.0,28.0,18.0,18.07,4.0,1.0,1643.06,38.629786,220.0,47.252408,171.356323,340.492936,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
22633,14.0,73823.84,6130.986667,7.0,6.0,13.0,6.0,52.0,11.0,16.39,6.0,1.0,1949.73,30.903403,149.0,356.365478,10000.000000,365.293462,0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0
22632,14.0,73823.84,6130.986667,7.0,6.0,30.0,3.0,52.0,11.0,18.39,6.0,1.0,1949.73,38.402913,148.0,356.365478,241.511502,265.221686,1,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0
72886,14.0,36228.20,2991.016667,8.0,7.0,34.0,2.0,27.0,18.0,18.07,4.0,1.0,1643.06,31.929426,221.0,47.252408,309.026521,232.822738,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76381,95.0,68484.44,3095.978333,5.0,7.0,5.0,5.0,12.0,20.0,12.52,8.0,1.0,105.41,28.430067,149.0,225.535667,220.000806,382.867193,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0
37190,95.0,46162.62,3548.885000,10.0,5.0,16.0,2.0,43.0,19.0,6.45,6.0,0.0,1788.63,35.386419,185.0,65.956819,288.645844,290.285837,1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
63619,95.0,28169.69,2171.474167,7.0,3.0,15.0,0.0,13.0,16.0,9.41,8.0,1.0,330.54,28.901025,349.0,0.000000,146.166716,340.980700,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
27925,99.0,35520.48,2697.040000,3.0,5.0,4.0,0.0,5.0,10.0,4.63,6.0,1.0,994.53,26.680333,219.0,0.000000,98.862070,430.841930,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
28509,100.0,30819.56,2547.296667,7.0,3.0,9.0,4.0,8.0,775.0,7.68,5.0,1.0,401.26,39.025723,173.0,96.848591,28.766089,369.114986,1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0

In [6]:
df3 = pd.read_csv("test.csv", low_memory=False)
df3['Month'].value_counts()

September    12500
October      12500
November     12500
December     12500
Name: Month, dtype: int64

No rows with decimal values in the 'Age' column.

In [16]:
df.sort_values(by='Num_Credit_Card', ascending=True)

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance,Credit_Score,Credit-Builder Loan,Personal Loan,Debt Consolidation Loan,Student Loan,Payday Loan,Mortgage Loan,Auto Loan,Home Equity Loan,Occupation_Accountant,Occupation_Architect,Occupation_Developer,Occupation_Doctor,Occupation_Engineer,Occupation_Entrepreneur,Occupation_Journalist,Occupation_Lawyer,Occupation_Manager,Occupation_Mechanic,Occupation_Media_Manager,Occupation_Musician,Occupation_Scientist,Occupation_Teacher,Occupation_Writer,Payment_of_Min_Amount_No,Payment_of_Min_Amount_Yes,Payment_Behaviour_High_spent_Large_value_payments,Payment_Behaviour_High_spent_Medium_value_payments,Payment_Behaviour_High_spent_Small_value_payments,Payment_Behaviour_Low_spent_Large_value_payments,Payment_Behaviour_Low_spent_Medium_value_payments,Payment_Behaviour_Low_spent_Small_value_payments
58296,21.0,106525.29,9040.107500,0.0,6.0,6.0,1.0,10.0,0.0,7.13,4.0,2.0,147.500,31.623519,219.0,78.271158,335.562941,770.176651,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
54133,48.0,63199.96,5426.663333,0.0,5.0,1.0,0.0,-4.0,11.0,11.01,7.0,2.0,1435.610,27.523596,219.0,0.000000,317.902142,484.764191,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0
90802,49.0,116224.68,9873.390000,0.0,3.0,8.0,1.0,10.0,0.0,5.01,0.0,2.0,1388.020,35.402331,392.0,59.586054,870.311777,327.441169,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
90801,49.0,116224.68,9873.390000,0.0,3.0,8.0,1.0,10.0,0.0,5.01,0.0,2.0,1388.020,41.906196,391.0,59.586054,249.835405,937.917542,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0
90800,49.0,116224.68,9873.390000,0.0,3.0,8.0,1.0,10.0,0.0,5.01,0.0,2.0,1388.020,26.642829,219.0,59.586054,816.496727,391.256219,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94130,37.0,20961.27,1833.772500,11.0,11.0,16.0,3.0,39.0,18.0,7.12,12.0,1.0,1917.280,31.053379,195.0,43.215031,177.764295,242.397924,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
94131,37.0,20961.27,1833.772500,11.0,11.0,16.0,3.0,39.0,14.0,7.12,13.0,1.0,1917.280,33.751008,196.0,43.215031,56.834019,333.328201,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0
94132,37.0,20961.27,1833.772500,11.0,11.0,16.0,3.0,39.0,18.0,7.12,6.0,1.0,1917.280,36.514531,197.0,43.215031,71.438549,318.723670,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
94133,37.0,20961.27,1833.772500,11.0,11.0,16.0,3.0,44.0,18.0,7.12,13.0,1.0,1917.280,30.238067,198.0,43.215031,69.855570,320.306649,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
74325,19.0,81338.16,6642.180000,11.0,10.0,33.0,3.0,18.0,15.0,9.41,12.0,0.0,1166.155,35.065436,172.0,356.766533,359.889471,207.561997,1,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0